{
  // "This config file is used to compile the blockly code base."
  "id": "blockly-config",
  "paths": [],
  "inputs": [//'testalert.js'
    //blockly.js must come first
    '../lib/blockly/core/blockly.js',

    // Blockly core translations
    //msg/js/*.js has to come next (for constants)
    '../lib/blockly/msg/js/ko.js',
    '../lib/blockly/msg/js/es.js',
    '../lib/blockly/msg/js/zh-hant.js',
    '../lib/blockly/msg/js/zh-hans.js',
    '../lib/blockly/msg/js/fr.js',
    '../lib/blockly/msg/js/it.js',
    '../lib/blockly/msg/js/ru.js',
    '../lib/blockly/msg/js/sv.js',
    '../lib/blockly/msg/js/nl.js',
    '../lib/blockly/msg/js/pt-br.js',
    '../lib/blockly/msg/js/pt.js',
    '../lib/blockly/msg/js/hu.js',
    '../lib/blockly/msg/js/de.js',
    '../lib/blockly/msg/js/pl.js',
    // English should always come last as the base language
    '../lib/blockly/msg/js/en.js',

    // App Inventor-specific translations
    /*'./src/msg/ko_kr/_messages.js',
    './src/msg/es_es/_messages.js',
    './src/msg/zh_tw/_messages.js',
    './src/msg/zh_cn/_messages.js',
    './src/msg/fr_fr/_messages.js',
    './src/msg/it_it/_messages.js',
    './src/msg/ru/_messages.js',
    './src/msg/sv/_messages.js',
    './src/msg/pt_br/_messages.js',
    './src/msg/pt/_messages.js',
    './src/msg/hu/_messages.js',
    './src/msg/nl/_messages.js',
    './src/msg/de/_messages.js',
    './src/msg/pl/_messages.js',*/
    // English should always come last as the base language
    './src/msg/en/_messages.js',

    // Lyn's instrumentation code
    "./src/instrument.js",

    //the rest of the blockly .js files can come in any order
    '../lib/blockly/core/block_animations.js',
    '../lib/blockly/core/block_drag_surface.js',
    '../lib/blockly/core/block_dragger.js',
    '../lib/blockly/core/block_events.js',
    '../lib/blockly/core/block_svg.js',
    '../lib/blockly/core/block.js',
    '../lib/blockly/core/blockly.js',
    '../lib/blockly/core/blocks.js',
    '../lib/blockly/core/bubble_dragger.js',
    '../lib/blockly/core/bubble.js',
    '../lib/blockly/core/comment.js',
    '../lib/blockly/core/components/component.js',
    '../lib/blockly/core/components/menu/menu.js',
    '../lib/blockly/core/components/menu/menuitem.js',
    '../lib/blockly/core/components/tree/basenode.js',
    '../lib/blockly/core/components/tree/treecontrol.js',
    '../lib/blockly/core/components/tree/treenode.js',
    '../lib/blockly/core/connection_db.js',
    '../lib/blockly/core/connection.js',
    '../lib/blockly/core/constants.js',
    '../lib/blockly/core/contextmenu.js',
    '../lib/blockly/core/css.js',
    '../lib/blockly/core/dropdowndiv.js',
    '../lib/blockly/core/events_abstract.js',
    '../lib/blockly/core/events.js',
    '../lib/blockly/core/extensions.js',
    '../lib/blockly/core/field_angle.js',
    '../lib/blockly/core/field_checkbox.js',
    '../lib/blockly/core/field_colour.js',
    '../lib/blockly/core/field_date.js',
    '../lib/blockly/core/field_dropdown.js',
    '../lib/blockly/core/field_image.js',
    '../lib/blockly/core/field_label_serializable.js',
    '../lib/blockly/core/field_label.js',
    '../lib/blockly/core/field_multilineinput.js',
    '../lib/blockly/core/field_number.js',
    '../lib/blockly/core/field_registry.js',
    '../lib/blockly/core/field_textinput.js',
    '../lib/blockly/core/field_variable.js',
    '../lib/blockly/core/field.js',
    '../lib/blockly/core/flyout_base.js',
    '../lib/blockly/core/flyout_button.js',
    '../lib/blockly/core/flyout_dragger.js',
    '../lib/blockly/core/flyout_horizontal.js',
    '../lib/blockly/core/flyout_vertical.js',
    '../lib/blockly/core/generator.js',
    '../lib/blockly/core/gesture.js',
    '../lib/blockly/core/grid.js',
    '../lib/blockly/core/icon.js',
    '../lib/blockly/core/inject.js',
    '../lib/blockly/core/input.js',
    '../lib/blockly/core/insertion_marker_manager.js',
    '../lib/blockly/core/keyboard_nav/action.js',
    '../lib/blockly/core/keyboard_nav/ast_node.js',
    '../lib/blockly/core/keyboard_nav/basic_cursor.js',
    '../lib/blockly/core/keyboard_nav/cursor.js',
    '../lib/blockly/core/keyboard_nav/flyout_cursor.js',
    '../lib/blockly/core/keyboard_nav/key_map.js',
    '../lib/blockly/core/keyboard_nav/marker.js',
    '../lib/blockly/core/keyboard_nav/navigation.js',
    '../lib/blockly/core/keyboard_nav/tab_navigate_cursor.js',
    '../lib/blockly/core/marker_manager.js',
    '../lib/blockly/core/msg.js',
    '../lib/blockly/core/mutator.js',
    '../lib/blockly/core/names.js',
    '../lib/blockly/core/options.js',
    '../lib/blockly/core/procedures.js',
    '../lib/blockly/core/rendered_connection.js',
    '../lib/blockly/core/renderers/common/block_rendering.js',
    '../lib/blockly/core/renderers/common/constants.js',
    '../lib/blockly/core/renderers/common/debugger.js',
    '../lib/blockly/core/renderers/common/drawer.js',
    '../lib/blockly/core/renderers/common/i_path_object.js',
    '../lib/blockly/core/renderers/common/info.js',
    '../lib/blockly/core/renderers/common/marker_svg.js',
    '../lib/blockly/core/renderers/common/path_object.js',
    '../lib/blockly/core/renderers/common/renderer.js',
    '../lib/blockly/core/renderers/geras/constants.js',
    '../lib/blockly/core/renderers/geras/drawer.js',
    '../lib/blockly/core/renderers/geras/highlight_constants.js',
    '../lib/blockly/core/renderers/geras/highlighter.js',
    '../lib/blockly/core/renderers/geras/info.js',
    '../lib/blockly/core/renderers/geras/measurables/inputs.js',
    '../lib/blockly/core/renderers/geras/path_object.js',
    '../lib/blockly/core/renderers/geras/renderer.js',
    '../lib/blockly/core/renderers/measurables/base.js',
    '../lib/blockly/core/renderers/measurables/connections.js',
    '../lib/blockly/core/renderers/measurables/inputs.js',
    '../lib/blockly/core/renderers/measurables/row_elements.js',
    '../lib/blockly/core/renderers/measurables/rows.js',
    '../lib/blockly/core/renderers/measurables/types.js',
    '../lib/blockly/core/renderers/minimalist/constants.js',
    '../lib/blockly/core/renderers/minimalist/drawer.js',
    '../lib/blockly/core/renderers/minimalist/info.js',
    '../lib/blockly/core/renderers/minimalist/renderer.js',
    '../lib/blockly/core/renderers/thrasos/info.js',
    '../lib/blockly/core/renderers/thrasos/renderer.js',
    '../lib/blockly/core/renderers/zelos/constants.js',
    '../lib/blockly/core/renderers/zelos/drawer.js',
    '../lib/blockly/core/renderers/zelos/info.js',
    '../lib/blockly/core/renderers/zelos/marker_svg.js',
    '../lib/blockly/core/renderers/zelos/measurables/inputs.js',
    '../lib/blockly/core/renderers/zelos/measurables/row_elements.js',
    '../lib/blockly/core/renderers/zelos/measurables/rows.js',
    '../lib/blockly/core/renderers/zelos/path_object.js',
    '../lib/blockly/core/renderers/zelos/renderer.js',
    '../lib/blockly/core/requires.js',
    '../lib/blockly/core/scrollbar.js',
    '../lib/blockly/core/theme/classic.js',
    '../lib/blockly/core/theme/dark.js',
    '../lib/blockly/core/theme/deuteranopia.js',
    '../lib/blockly/core/theme/highcontrast.js',
    '../lib/blockly/core/theme/modern.js',
    '../lib/blockly/core/theme/tritanopia.js',
    '../lib/blockly/core/theme/zelos.js',
    '../lib/blockly/core/theme_manager.js',
    '../lib/blockly/core/theme.js',
    '../lib/blockly/core/toolbox.js',
    '../lib/blockly/core/tooltip.js',
    '../lib/blockly/core/touch_gesture.js',
    '../lib/blockly/core/touch.js',
    '../lib/blockly/core/trashcan.js',
    '../lib/blockly/core/ui_events.js',
    '../lib/blockly/core/ui_menu_utils.js',
    '../lib/blockly/core/utils/aria.js',
    '../lib/blockly/core/utils/colour.js',
    '../lib/blockly/core/utils/coordinate.js',
    '../lib/blockly/core/utils/dom.js',
    '../lib/blockly/core/utils/global.js',
    '../lib/blockly/core/utils/idgenerator.js',
    '../lib/blockly/core/utils/keycodes.js',
    '../lib/blockly/core/utils/math.js',
    '../lib/blockly/core/utils/object.js',
    '../lib/blockly/core/utils/rect.js',
    '../lib/blockly/core/utils/size.js',
    '../lib/blockly/core/utils/string.js',
    '../lib/blockly/core/utils/style.js',
    '../lib/blockly/core/utils/svg_paths.js',
    '../lib/blockly/core/utils/useragent.js',
    '../lib/blockly/core/utils/xml.js',
    '../lib/blockly/core/utils.js',
    '../lib/blockly/core/variable_events.js',
    '../lib/blockly/core/variable_map.js',
    '../lib/blockly/core/variable_model.js',
    '../lib/blockly/core/variables_dynamic.js',
    '../lib/blockly/core/variables.js',
    '../lib/blockly/core/warning.js',
    '../lib/blockly/core/widgetdiv.js',
    '../lib/blockly/core/workspace_audio.js',
    '../lib/blockly/core/workspace_comment_render_svg.js',
    '../lib/blockly/core/workspace_comment_svg.js',
    '../lib/blockly/core/workspace_comment.js',
    '../lib/blockly/core/workspace_drag_surface_svg.js',
    '../lib/blockly/core/workspace_dragger.js',
    '../lib/blockly/core/workspace_events.js',
    '../lib/blockly/core/workspace_svg.js',
    '../lib/blockly/core/workspace.js',
    '../lib/blockly/core/ws_comment_events.js',
    '../lib/blockly/core/xml.js',
    '../lib/blockly/core/zoom_controls.js',

    //finally, include any of our own .js file in any order
    "./src/events.js",
    "./src/blocklyeditor.js",
    './src/typeblock.js',
    "./src/blockly.js",
    "./src/events.js",
    "./src/block.js",
    "./src/workspace.js",
    "./src/xml.js",
    "./src/trashcan.js",
    "./src/scrollbar.js",
    "./src/block_svg.js",
    "./src/connection_db.js",
    "./src/component_database.js",
    "./src/procedure_database.js",
    "./src/variable_database.js",
    "./src/workspace_svg.js",
    "./src/blockColors.js",
    "./src/translation_properties.js",
    "./src/translation_events.js",
    "./src/translation_methods.js",
    "./src/translation_params.js",
    "./src/drawer.js",
    "./src/savefile.js",
    "./src/versioning.js",
    "./src/mutators.js",
    "./src/field_lexical_variable.js",
    "./src/errorIcon.js",
    "./src/warningHandler.js",
    "./src/field_procedure.js",
    "./src/field_textblockinput.js",
    "./src/warningIndicator.js",
    "./src/exportBlocksImage.js",
    "./src/flydown.js",
    "./src/field_flydown.js",
    "./src/field_parameter_flydown.js",
    "./src/field_global_flydown.js",
    "./src/field_procedurename.js",
    "./src/nameSet.js",
    "./src/substitution.js",
    "./src/language_switch.js",
    "./src/warning.js",
    "./src/toolboxController.js",
    "./src/field.js",
    "./src/rendered_connection.js",
    "./src/input.js",

    // Dialog Utiltiy
    "./src/util.js",

    // backpack files
    "./src/backpack.js",
    "./src/backpackFlyout.js",

    //blocks files
    './src/blocks/control.js',
    './src/blocks/logic.js',
    './src/blocks/text.js',
    './src/blocks/lists.js',
    './src/blocks/math.js',
    './src/blocks/utilities.js',
    './src/blocks/procedures.js',
    './src/blocks/lexical-variables.js',
    './src/blocks/colors.js',
    './src/blocks/components.js',
    './src/blocks/dictionaries.js',

    //generator files
    "./src/generators/yail.js",
    "./src/generators/yail/componentblock.js",
    "./src/generators/yail/lists.js",
    "./src/generators/yail/math.js",
    "./src/generators/yail/control.js",
    "./src/generators/yail/logic.js",
    "./src/generators/yail/text.js",
    "./src/generators/yail/colors.js",
    "./src/generators/yail/variables.js",
    "./src/generators/yail/procedures.js",
    "./src/generators/yail/dictionaries.js",

    // Repl
    "./src/replmgr.js",

    // extras
    "./src/extras.js"
    ],

  // This must be specified because datetimesymbols.js from the Closure Library
  // will be included, so when test-raw.html loads each input in RAW mode,
  // it is important that the proper charset be used.
  "output-charset": "UTF-8",
  "mode": "RAW",
  //"mode": "SIMPLE",
//  "mode" : "WHITESPACE_ONLY",
  "experimental-compiler-options": {
    "languageIn": "ECMASCRIPT5"
  },
  "closure-library" : "../lib/closure-library/closure/goog",
  "output-file": "../build/blocklyeditor/blockly-all.js"
}
